import type { Academy } from '../types';

export const mockAcademies: Academy[] = [
    {
        id: 1,
        name: '한국소프트웨어인재개발원',
        description: '배움을 넘어 희망을 이룰 수 있는 곳, KOSMO와 함께해요!',
        logoUrl: '',
        address: '서울 강남구 테헤란로 212',
        phone: '02-1234-5678',
        email: 'info@kosmo.or.kr',
        businessNumber: '123-45-67890',
        approvalStatus: 'APPROVED',
        fields: ['웹개발', '데이터/AI'],
        rating: 4.5,
        reviewCount: 128,
    },
    {
        id: 2,
        name: '멋쟁이사자처럼',
        description: '누구나 가능성을 현실로 만들 수 있도록! 13년 교육 노하우의 국비지원 부트캠프',
        logoUrl: '',
        address: '서울 강남구 테헤란로 427',
        phone: '02-2345-6789',
        email: 'edu@likelion.net',
        businessNumber: '234-56-78901',
        approvalStatus: 'APPROVED',
        fields: ['웹개발', '모바일', '데이터/AI'],
        rating: 4.7,
        reviewCount: 356,
    },
    {
        id: 3,
        name: '팀스파르타',
        description: '누구나 큰일 낼 수 있는 세상을 위한, 모두를 위한 SW교육',
        logoUrl: '',
        address: '서울 강남구 테헤란로 311',
        phone: '02-3456-7890',
        email: 'hello@teamsparta.co',
        businessNumber: '345-67-89012',
        approvalStatus: 'APPROVED',
        fields: ['웹개발', '모바일', '데이터/AI'],
        rating: 4.6,
        reviewCount: 512,
    },
    {
        id: 4,
        name: 'F-Lab',
        description: '상위 1% 개발자들의 멘토링',
        logoUrl: '',
        address: '서울 강남구 논현로 508',
        phone: '02-4567-8901',
        email: 'support@f-lab.kr',
        businessNumber: '456-78-90123',
        approvalStatus: 'APPROVED',
        fields: ['웹개발'],
        rating: 4.9,
        reviewCount: 89,
    },
    {
        id: 5,
        name: '패스트캠퍼스',
        description: '우리는 지금 누군가의 인생을 바꾸는 일을 하고 있습니다.',
        logoUrl: '',
        address: '서울 강남구 강남대로 364',
        phone: '02-5678-9012',
        email: 'help@fastcampus.co.kr',
        businessNumber: '567-89-01234',
        approvalStatus: 'APPROVED',
        fields: ['웹개발', '데이터/AI'],
        rating: 4.4,
        reviewCount: 2340,
    },
];
